linters:
  enable-all: true

  disable:
    # Deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

    # Other disabled linters
    - exhaustruct
    - wrapcheck
    - wsl

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/jamesalexatkin/tfl-go
          - github.com/stretchr/testify/require

issues:
  include:
    - EXC0012 # revive: Enforces comments on exported members
    - EXC0014 # revive: Enforces comment style on exported members
    